#

name: barneymanCI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:

#  schedule:
#    - cron:  '*/30 * * * *'    
#    - cron:  '10 * * * *'    
  
  #release:
    # can get to the payload of the request https://developer.github.com/v3/repos/releases/#create-a-release
    # via github.event.release.
    #types: [published]

  push:
    branches: [ master ]
    
    tags:
      - v*

  pull_request:
    types: [opened, synchronize, reopened]

  #   branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # output some env vars, for later use :)
  paintEnvs:
    runs-on: ubuntu-latest
    steps:
      # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#contexts
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "github.event_name"
          echo "${{ github.event_name }}"
          echo "github.ref"
          echo "${{ github.ref }}"
          echo "$GITHUB_CONTEXT"

  createRelease:
    runs-on: ubuntu-latest
    steps:

      # create a change listing (from the previous release )
      # - name: Changelog
      #   if: ${{ github.event_name == 'create' }}
      #   uses: scottbrenner/generate-changelog-action@master
      #   id: Changelog

      - name: Create Release
        # no need if we're doing a build after push
        if: ${{ github.event_name == 'create' }}
        id: create_release
        uses: actions/create-release@latest
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          # https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
          tag_name: ${{ github.ref }}
          # must use another release name! Release ${{ github.ref }} got created to get here
          release_name: Release ${{ github.run_id }} (from Action)
          # ${{ github.event.release.body }}
          body: | 
            Release
          # save it as draft until all assets are uploaded, then undraft it at the end
          draft: true
          prerelease: ${{endsWith(github.ref,'pr')}}
  
      - name: Output Release URL File
        # no need if we're doing a build after push
        if: ${{ github.event_name == 'create' }}
        run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
        
      - name: Save Release URL File for publish
        # no need if we're doing a build after push
        if: ${{ github.event_name == 'create' }}
        uses: actions/upload-artifact@v1
        with:
          name: release_url
          path: release_url.txt  

      - name: Output Release ID File
        # no need if we're doing a build after push
        if: ${{ github.event_name == 'create' }}
        run: echo "${{ steps.create_release.outputs.id }}" > release_id.txt

      - name: Save Release ID File for publish
        # no need if we're doing a build after push
        if: ${{ github.event_name == 'create' }}
        uses: actions/upload-artifact@v1
        with:
          name: release_id
          path: release_id.txt  

      - name: Null task
        if: ${{ github.event_name == 'push' }}
        run: echo "push build"


  # This workflow contains a single job called "build"
  builder:
    needs: [createRelease]

    # create a matrix 
    # wemos d1 - esp8266:esp8266:d1
    strategy:
      matrix: 
        include:
          # unproven!
          - platform: "esp32cam"
            platform_options: "esp32:esp32:esp32wrover:PartitionScheme=min_spiffs,FlashMode=qio,FlashFreq=80,UploadSpeed=115200,DebugLevel=none"
            friendly: "esp32_cam"
            spiffsCmdLine: -p 256 -b 4096 -s 0x3D0000
            spiffsCmd: mkspiffs_esp32
          - platform: "sonoff"
            # have to use generic, because the sonoff board doesn't SDA & others defined
            # platform_options: "esp8266:esp8266:sonoff:BoardModel=sonoffBasic,xtal=80,vt=flash,exception=legacy,ssl=all,eesz=1M256,ip=lm2f,dbg=Disabled"
            platform_options: "esp8266:esp8266:generic:xtal=80,vt=iram,exception=disabled,stacksmash=disabled,ssl=all,mmu=3232,non32xfer=fast,ResetMethod=ck,CrystalFreq=26,FlashFreq=40,FlashMode=dout,eesz=1M128,led=13,sdk=nonosdk_190703,ip=lm2f,dbg=Disabled,lvl=None____,wipe=none,baud=115200"

            friendly: "sonoff_basic"
            spiffsCmdLine: -p 256 -b 4096 -s 0x20000
            spiffsCmd: mkspiffs_esp8266
          - platform: "d1_mini"
            platform_options: "esp8266:esp8266:d1_mini:xtal=80,vt=iram,exception=disabled,ssl=all,eesz=4M1M,ip=lm2f,dbg=Disabled"
            friendly: "wemosD1"        
            spiffsCmdLine: -p 256 -b 8192 -s 0xFA000
            spiffsCmd: mkspiffs_esp8266
            # 1028096:  

    # The type of runner that the job will run on
    # to get py 2.7
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1

      - name: EnvironmentForRelease
        if: ${{ github.event_name == 'create' }}
        # remove refs/tags/ from github-ref
        run: |
          echo "setting up env for release ..."
          echo ${GITHUB_REF}
          echo ${GITHUB_REPOSITORY}
          echo "NEW_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "NEW_HEAD=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: EnvironmentForPush
        if: ${{ github.event_name == 'push' }}
        # remove refs/tags/ from github-ref
        run: |
          echo "setting up env for push ..."
          echo ${GITHUB_REF}
          echo ${GITHUB_REPOSITORY}
          echo "NEW_TAG=${{ steps.version.outputs.version }}" >> $GITHUB_ENV
          echo "NEW_HEAD=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checking out tag ${{ github.ref }}
        uses: actions/checkout@master
        with:
          submodules: "true"
          ref: ${{ github.ref }}

      - name: gzip web content
        run: |
          cd ./data
          gzip -v *.htm
          gzip -v *.css
          cd ..

      # esp32cam builder needs py
      # https://github.com/marketplace/actions/python-dependency-installation 
      # esp32 esptool needs serial
      - name: install py
        if: ${{ matrix.friendly == 'esp32_cam' }}
        uses: actions/setup-python@v4
        with:
          python-version: '2.7.18'

      # esp32 needs serial around to build successfully
      - name: Install Python dependencies
        if: ${{ matrix.friendly == 'esp32_cam' }}
        uses: py-actions/py-dependency-install@v2      
     
      
      # We use the arduino/setup-arduino-cli action to install and
      # configure the Arduino CLI on the system.
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
        with:
          version: "0.22.0"
      
      - name: Install platform
        run: |
          arduino-cli core update-index --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json,https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp8266:esp8266@3.0.2 --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core install esp32:esp32@2.0.2 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      # Finally, we compile the sketch, using the FQBN that was set
      # in the build matrix.
      - name: Compile Sketch Matrix
        run: arduino-cli compile --fqbn ${{ matrix.platform_options }} --output-dir . --build-property compiler.cpp.extra_flags="-D_VERSION_FRIENDLY_CLI=${{ matrix.friendly }} -D_VERSION_NUM_CLI=${{ env.NEW_TAG }}"  --libraries ./libraries ESP8266-Light-Switch

      - name: rename output
        run: |
          mv ESP8266-Light-Switch.ino.elf ${{ matrix.friendly }}_${GITHUB_RUN_ID}.elf
          mv ESP8266-Light-Switch.ino.bin ${{ matrix.friendly }}_${GITHUB_RUN_ID}.bin

      # then handle spiffs
      - name: Install mkspiffs
        # no need if a push build
        # if: ${{ github.event_name == 'create' }}
        run: |
          # ESP32 ver
          wget https://github.com/igrr/mkspiffs/releases/download/0.2.3/mkspiffs-0.2.3-arduino-esp32-linux64.tar.gz
          tar -xvf mkspiffs-0.2.3-arduino-esp32-linux64.tar.gz --strip-components 1
          mv mkspiffs mkspiffs_esp32
          # ESP8266 ver
          wget https://github.com/igrr/mkspiffs/releases/download/0.2.3/mkspiffs-0.2.3-arduino-esp8266-linux64.tar.gz
          tar -xvf mkspiffs-0.2.3-arduino-esp8266-linux64.tar.gz --strip-components 1
          mv mkspiffs mkspiffs_esp8266

      - name: Create SPIFFS
        # no need if a push build
        # if: ${{ github.event_name == 'create' }}
        run: ./${{ matrix.spiffsCmd }} -c ./data ${{ matrix.spiffsCmdLine }} ${{ matrix.friendly }}_${GITHUB_RUN_ID}.spiffs

      # compress deliverables
      - name: Compress output
        # no need if a push build
        # if: ${{ github.event_name == 'create' }}
        run: tar -czvf ${{ matrix.friendly }}.tar.gz *.elf *.bin *.spiffs
        
      - name: Load Release URL File from release job
        # no need if a push build
        if: ${{ github.event_name == 'create' }}
        uses: actions/download-artifact@v1
        with:
          name: release_url

      - name: Get Release File Name & Upload URL
        # no need if a push build
        if: ${{ github.event_name == 'create' }}
        id: get_release_info
        run: |
          value=`cat release_url/release_url.txt`
          echo ::set-output name=upload_url::$value
      
      - name: Upload artifacts
        if: ${{ github.event_name != 'create' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.friendly }}
          path: ${{ matrix.friendly }}.tar.gz


      - name: Upload Release Asset
        # no need if a push build
        if: ${{ github.event_name == 'create' }}
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.get_release_info.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
            asset_path: ./${{ matrix.friendly }}.tar.gz
            asset_name: ${{ matrix.friendly }}_${{ env.NEW_TAG }}.tar.gz
            asset_content_type: application/tar+gzip            
        
  undraft:
    runs-on: ubuntu-latest
    # no need if a push build
    if: ${{ github.event_name == 'create' }}
    needs: [builder]
    steps:
      - name: Load Release ID File from release job
        uses: actions/download-artifact@v1
        with:
          name: release_id
      - name: Get Release File Name & id
        id: get_release_id
        run: |
          value=`cat release_id/release_id.txt`
          echo ::set-output name=release_id::$value
          
      - uses: octokit/request-action@v2.x
        id: changeDraft
        with:
          route: PATCH /repos/{repository}/releases/{id}
          repository: ${{ github.repository }}
          id: ${{ steps.get_release_id.outputs.release_id }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
